# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationForm(object):
    def setupUi(self, AuthorizationForm):
        AuthorizationForm.setObjectName("AuthorizationForm")
        AuthorizationForm.resize(231, 109)
        self.loginWidget = QtWidgets.QWidget(AuthorizationForm)
        self.loginWidget.setObjectName("loginWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.loginWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.login = QtWidgets.QLineEdit(self.loginWidget)
        self.login.setText("")
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 0, 1, 2)
        self.confirmButton = QtWidgets.QPushButton(self.loginWidget)
        self.confirmButton.setAutoDefault(False)
        self.confirmButton.setDefault(False)
        self.confirmButton.setObjectName("confirmButton")
        self.gridLayout.addWidget(self.confirmButton, 1, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.loginWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 0, 1, 1)
        AuthorizationForm.setCentralWidget(self.loginWidget)

        self.retranslateUi(AuthorizationForm)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationForm)

    def retranslateUi(self, AuthorizationForm):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationForm.setWindowTitle(_translate("AuthorizationForm", "Вход"))
        self.login.setPlaceholderText(_translate("AuthorizationForm", "Логин"))
        self.confirmButton.setText(_translate("AuthorizationForm", "Войти"))
        self.cancelButton.setText(_translate("AuthorizationForm", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthorizationForm = QtWidgets.QMainWindow()
    ui = Ui_AuthorizationForm()
    ui.setupUi(AuthorizationForm)
    AuthorizationForm.show()
    sys.exit(app.exec_())
