# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuyWindow(object):
    def setupUi(self, BuyWindow):
        BuyWindow.setObjectName("BuyWindow")
        BuyWindow.resize(231, 109)
        self.buyWidget = QtWidgets.QWidget(BuyWindow)
        self.buyWidget.setObjectName("buyWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.buyWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.amount = QtWidgets.QLineEdit(self.buyWidget)
        self.amount.setText("")
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 0, 0, 1, 2)
        self.buyButton = QtWidgets.QPushButton(self.buyWidget)
        self.buyButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 85)")
        self.buyButton.setAutoDefault(False)
        self.buyButton.setDefault(False)
        self.buyButton.setObjectName("buyButton")
        self.gridLayout.addWidget(self.buyButton, 1, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.buyWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 0, 1, 1)
        BuyWindow.setCentralWidget(self.buyWidget)

        self.retranslateUi(BuyWindow)
        QtCore.QMetaObject.connectSlotsByName(BuyWindow)

    def retranslateUi(self, BuyWindow):
        _translate = QtCore.QCoreApplication.translate
        BuyWindow.setWindowTitle(_translate("BuyWindow", "MainWindow"))
        self.amount.setPlaceholderText(_translate("BuyWindow", "Количество"))
        self.buyButton.setText(_translate("BuyWindow", "Купить"))
        self.cancelButton.setText(_translate("BuyWindow", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BuyWindow = QtWidgets.QMainWindow()
    ui = Ui_BuyWindow()
    ui.setupUi(BuyWindow)
    BuyWindow.show()
    sys.exit(app.exec_())
