# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sell_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SellWindow(object):
    def setupUi(self, SellWindow):
        SellWindow.setObjectName("SellWindow")
        SellWindow.resize(231, 109)
        self.sellWidget = QtWidgets.QWidget(SellWindow)
        self.sellWidget.setObjectName("sellWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.sellWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.amount = QtWidgets.QLineEdit(self.sellWidget)
        self.amount.setText("")
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 0, 0, 1, 2)
        self.sellButton = QtWidgets.QPushButton(self.sellWidget)
        self.sellButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(206, 66, 66)")
        self.sellButton.setAutoDefault(False)
        self.sellButton.setDefault(False)
        self.sellButton.setObjectName("sellButton")
        self.gridLayout.addWidget(self.sellButton, 1, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.sellWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 0, 1, 1)
        SellWindow.setCentralWidget(self.sellWidget)

        self.retranslateUi(SellWindow)
        QtCore.QMetaObject.connectSlotsByName(SellWindow)

    def retranslateUi(self, SellWindow):
        _translate = QtCore.QCoreApplication.translate
        SellWindow.setWindowTitle(_translate("SellWindow", "MainWindow"))
        self.amount.setPlaceholderText(_translate("SellWindow", "Количество"))
        self.sellButton.setText(_translate("SellWindow", "Продать"))
        self.cancelButton.setText(_translate("SellWindow", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellWindow = QtWidgets.QMainWindow()
    ui = Ui_SellWindow()
    ui.setupUi(SellWindow)
    SellWindow.show()
    sys.exit(app.exec_())
